// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkUZIn33CKRurON0hxZKagSLFciWArR2k',
    appId: '1:833900910992:web:31a310b7b8ac42a8fcfb15',
    messagingSenderId: '833900910992',
    projectId: 'athkary-f5eaf',
    authDomain: 'athkary-f5eaf.firebaseapp.com',
    databaseURL: 'https://athkary-f5eaf-default-rtdb.firebaseio.com',
    storageBucket: 'athkary-f5eaf.firebasestorage.app',
    measurementId: 'G-8LQLXDE444',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLv_v43ZKKZmI0Iez46UDv8sGCgQenVhA',
    appId: '1:833900910992:android:f5e76bd97fcf47d6fcfb15',
    messagingSenderId: '833900910992',
    projectId: 'athkary-f5eaf',
    databaseURL: 'https://athkary-f5eaf-default-rtdb.firebaseio.com',
    storageBucket: 'athkary-f5eaf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMrpzQr7V68BGPLlLPNmkbJXGkKmS0eY8',
    appId: '1:833900910992:ios:3605d4df7542e02afcfb15',
    messagingSenderId: '833900910992',
    projectId: 'athkary-f5eaf',
    databaseURL: 'https://athkary-f5eaf-default-rtdb.firebaseio.com',
    storageBucket: 'athkary-f5eaf.firebasestorage.app',
    iosBundleId: 'com.example.athkary',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMrpzQr7V68BGPLlLPNmkbJXGkKmS0eY8',
    appId: '1:833900910992:ios:3605d4df7542e02afcfb15',
    messagingSenderId: '833900910992',
    projectId: 'athkary-f5eaf',
    databaseURL: 'https://athkary-f5eaf-default-rtdb.firebaseio.com',
    storageBucket: 'athkary-f5eaf.firebasestorage.app',
    iosBundleId: 'com.example.athkary',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkUZIn33CKRurON0hxZKagSLFciWArR2k',
    appId: '1:833900910992:web:d4366a5c18fac45cfcfb15',
    messagingSenderId: '833900910992',
    projectId: 'athkary-f5eaf',
    authDomain: 'athkary-f5eaf.firebaseapp.com',
    databaseURL: 'https://athkary-f5eaf-default-rtdb.firebaseio.com',
    storageBucket: 'athkary-f5eaf.firebasestorage.app',
    measurementId: 'G-HMZG6LRWL8',
  );

}